const CARDS = [
  { term: "Buoy", definition: "to keep afloat; a floating marker in a body of water" },
  { term: "Contemptible", definition: "deserving contempt" },
  { term: "Contrive", definition: "to form or make in a skillful or ingenious way" },
  { term: "Cuirass", definition: "a piece of armor covering the body from neck to waist" },
  { term: "Dire", definition: "warning of disaster" },
  { term: "Dreary", definition: "causing feelings of cheerlessness" },
  { term: "Eddy", definition: "a current moving in a circle like a whirlpool" },
  { term: "Entrails", definition: "internal parts" },
  { term: "Glower", definition: "to stare angrily" },
  { term: "Gorge", definition: "a narrow passage, ravine, or steep-walled canyon" },
  { term: "Grotto", definition: "an artificial recess or structure made to resemble a natural cave" },
  { term: "Heifer", definition: "a young cow" },
  { term: "Implacable", definition: "not placable: not capable of being appeased, pacified, or mitigated" },
  { term: "Imprudent", definition: "not prudent: lacking discretion, wisdom, or good judgment" },
  { term: "Impudent", definition: "showing contempt for or disregard of others" },
  { term: "Incredulous", definition: "tending to disbelieve" },
  { term: "Jest", definition: "a witty remark" },
  { term: "Keen", definition: "very alert and perceptive" },
  { term: "Laden", definition: "carrying a load or burden" },
  { term: "Libation", definition: "the act of pouring a liquid (as wine) in honor of a god; the liquid poured out" },
  { term: "Lithe", definition: "easily bent; gracefully limber" },
  { term: "Maelstrom", definition: "a whirlpool of great force and violence" },
  { term: "Maudlin", definition: "weakly and excessively sentimental" },
  { term: "Nock", definition: "to fit (an arrow) against the bowstring for shooting" },
  { term: "Petrel", definition: "any of various small long-winged seabirds (as the storm petrel) that fly far from land" },
  { term: "Provision", definition: "a measure taken beforehand, often to obtain materials or supplies needed" },
  { term: "Restitution", definition: "the restoring of something to its rightful owner; make things right" },
  { term: "Scud", definition: "to move or run swiftly especially as if driven forward; wind driven clouds or water" },
  { term: "Shroud", definition: "burial garment" },
  { term: "Taut", definition: "tightly drawn: not slack" },
];
